name: MCNSAChat
main: com.mcnsa.mcnsachat3.plugin.MCNSAChat3
version: 3.0.0.3-SNAPSHOT
authors: [maboughey, mcnsa, mcnsa.com]
depend: [PermissionsEx]

commands:
  cmute:
    description: Mute players
    usage: /<command>
  cto:
    description: Put a player in timeout
    usage: /<command> <player> <time in mins> <reason>
  cremove:
    description: Remove a player from a channel
    Usage: /<command> <player> <channel>